global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: docker_sd
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Only keep containers that is in the metrics-net
      - source_labels: [__meta_docker_network_name]
        regex: metrics-net
        action: keep
      # Only keep containers that have a prometheus_job label
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: .+
        action: keep
      # Extract the labels that are prefixed by prometheus
      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
      # Overwrite scrape port, if defined
      - source_labels: [__address__, __meta_docker_container_label_prometheus_scrape_port]
        target_label: __address__
        regex: (.+):\d+;(.+)
        replacement: $1:$2
      # drop labels with scrape_ prefix from final labels
      - regex: scrape_.+
        action: labeldrop
      # set instance to prefix + container name + private port
      - source_labels: [__meta_docker_container_name, __meta_docker_port_private]
        target_label: instance
        regex: (.+);(.+)
        replacement: this_server${1}:${2}


