version: '3'

volumes:
  prometheus_data:
  sd_data:


networks:
  metrics-net:
    # overriding name, otherwise the docker-compose project name will be prefixed
    name: metrics-net
    # consider creating it as external
    #external: true

services:
  prometheus:
    image: prom/prometheus:v2.39.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
      - sd_data:/sd_data:ro
    ports:
      - 9090:9090
    restart: always
    networks:
      - metrics-net
    labels:
      prometheus_job: prometheus

  discover:
    build: ../..
    command:
      - --instance-prefix=localhost
      - --output-file=/sd_data/docker_sd.yml
      - --refresh-interval=5s
      - --log-level=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - sd_data:/sd_data
    networks:
      - metrics-net
    ports:
      - 9200:9200
    restart: always
    labels:
      prometheus_job: docker_sd

  app_simple:
    build: ../app1
    environment:
      PORT: 2000
    labels:
      prometheus_job: job_app
      prometheus_coffee_roast: light
    restart: always
    expose:
      - 2000
    networks:
      - metrics-net

  app_no_job:
    build: ../app1
    restart: always
    networks:
      - metrics-net

  app_no_network:
    build: ../app1
    environment:
      PORT: 2000
    labels:
      prometheus_job: job_app
    restart: always
    expose:
      - 2000

  app_no_ports:
    build: ../app1
    labels:
      prometheus_job: job_app
    restart: always
    networks:
      - metrics-net

  app_not_explicit:
    build: ../app1
    environment:
      PORT: 2500
    labels:
      prometheus_job: job_app
    restart: always
    expose:
      - 2000
      - 2500
      - 3000
    networks:
      - metrics-net

  app_explicit:
    build: ../app1
    environment:
      PORT: 2500
    labels:
      prometheus_job: job_app
      prometheus_scrape_port: 2500
    restart: always
    expose:
      - 2000
      - 2500
      - 3000
    networks:
      - metrics-net
