global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules

scrape_configs:
  - job_name: docker_sd_file
    file_sd_configs:
      - files:
          - /sd_data/docker_sd.yml
