version: '3'

volumes:
  prometheus_data:

networks:
  metrics-net:  

services:
  prometheus:
    image: prom/prometheus:v2.39.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus      
    ports:
      - 9090:9090
    restart: always    

  app1:
    build: app1  
    labels:
      prometheus_job: job_app
      prometheus_key1: val1
    restart: always