version: '3'

volumes:
  prometheus_data:

networks:
  metrics-net:  
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.39.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus      
    ports:
      - 9090:9090
    restart: always    
    networks:
      - metrics-net

  app1:
    build: app1  
    environment:
      PORT: 2000
    labels:
      prometheus_job: job_app
      prometheus_key1: val1
      prometheus_scrape_port: 2001
      prometheus_scrape_interval: 7s
      prometheus_scrape_timeout: 14s
    restart: always
    expose: 
      - 2000
    networks:
      - metrics-net      